name: math228p2
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - matplotlib
  - numpy
  - pandas
  - scikit-learn
  - jupyter
  - jupyterlab
  - jupyter_contrib_nbextensions
pip:
  - tensorflow